export const SET_SEARCHED_USERS = "SET_SEARCHED_USERS"
export const SET_FETCHED_EVENTS = "SET_FETCHED_EVENTS"
export const GET_EVENT_DETAIL = "GET_EVENT_DETAIL"
export const SET_PLAY_EVENT = "SET_PLAY_EVENT"
export const SET_PUSHED_ROUTE = "SET_PUSHED_ROUTE"
export const SET_POP_ROUTE = "SET_POP_ROUTE"


export const SET_PLAYER_STATUS = "SET_PLAYER_STATUS"

export const SET_FETCHED_ARCHIVE_EVENTS_SUCCESS = "SET_FETCHED_ARCHIVE_EVENTS_SUCCESS"
export const SET_FETCHED_LIVE_EVENTS_SUCCESS = "SET_FETCHED_LIVE_EVENTS_SUCCESS"
export const SET_FETCHED_FUTURE_EVENTS_SUCCESS = "SET_FETCHED_FUTURE_EVENTS_SUCCESS"
export const SET_FETCHED_ARCHIVE_EVENTS_FAILED = "SET_FETCHED_ARCHIVE_EVENTS_FAILED"
export const SET_FETCHED_LIVE_EVENTS_FAILED = "SET_FETCHED_LIVE_EVENTS_FAILED"
export const SET_FETCHED_FUTURE_EVENTS_FAILED= "SET_FETCHED_FUTURE_EVENTS_FAILED"

export const SET_CATEGORY_CURRENT = "SET_CATEGORY_CURRENT"
export const SET_ONLOAD = "SET_ONLOAD"

export const SET_FETCHED_CATEGORY_SUCCESS = "SET_FETCHED_CATEGORY_SUCCESS"
export const SET_FETCHED_CATEGORY_FAILED = "SET_FETCHED_CATEGORY_FAILED"

export const SET_FETCHED_PAGE_SUCCESS = "SET_FETCHED_PAGE_SUCCESS"
export const SET_FETCHED_PAGE_FAILED = "SET_FETCHED_PAGE_FAILED"

export const SET_FETCHED_POST_SUCCESS = "SET_FETCHED_POST_SUCCESS"
export const SET_FETCHED_POST_FAILED = "SET_FETCHED_POST_FAILED"

export const SET_FETCHED_MEDIA_SUCCESS = "SET_FETCHED_MEDIA_SUCCESS"
export const SET_FETCHED_MEDIA_FAILED = "SET_FETCHED_MEDIA_FAILED"

export const NETWORK_STATE = "NETWORK_STATE"
export const NAV_HELPER = "NAV_HELPER"
export const SET_HEADER = "SET_HEADER"
export const SET_CUSTOMEVENT = "SET_CUSTOMEVENT"
export const SET_URL = "SET_URL"